In [3]:
import numpy as bat

In [2]:
import pandas as babu

In [3]:
a=bat.array([20,34,67,45,76])

In [8]:
print("View array :",a)

View array : [20 34 67 45 76]


In [9]:
print("Shape of array:",a.shape)

Shape of array: (5,)


In [13]:
b=babu.Series(['Arul','bat','babu','Thomas','suriya'])

In [14]:
print("View pandas:",b)

0      Arul
1       bat
2      babu
3    Thomas
4    suriya
dtype: str


In [16]:
d1=bat.array([23,56,77,90,100,45,23,76,54,82])
print("One Dimentional Array:",d1)

One Dimentional Array: [ 23  56  77  90 100  45  23  76  54  82]


In [24]:
multi=bat.array([[12,43,6,7,33],[45,67,99,2,54],[66,75,82,90,86]])
print("multi dimentional array:\n",multi)

multi dimentional array:
 [[12 43  6  7 33]
 [45 67 99  2 54]
 [66 75 82 90 86]]


In [23]:
zero=bat.zeros((4,5))
one=bat.ones((5,4))
print(zero)
print(one)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [4]:
df=babu.read_csv("C:/Users/ELCOT/Downloads/test_data.csv")

In [5]:
print("\n Data frame \n",df)


 Data frame 
     Unnamed: 0  PassengerId  Survived  Sex     Age      Fare  Pclass_1  \
0          791          792         0    1  0.2000  0.050749         0   
1          792          793         0    0  0.3500  0.135753         0   
2          793          794         0    1  0.3500  0.059914         1   
3          794          795         0    1  0.3125  0.015412         0   
4          795          796         0    1  0.4875  0.025374         0   
..         ...          ...       ...  ...     ...       ...       ...   
95         886          887         0    1  0.3375  0.025374         0   
96         887          888         1    0  0.2375  0.058556         1   
97         888          889         0    0  0.3500  0.045771         0   
98         889          890         1    1  0.3250  0.058556         1   
99         890          891         0    1  0.4000  0.015127         0   

    Pclass_2  Pclass_3  Family_size  Title_1  Title_2  Title_3  Title_4  \
0          1         

In [6]:
print(df.head())

   Unnamed: 0  PassengerId  Survived  Sex     Age      Fare  Pclass_1  \
0         791          792         0    1  0.2000  0.050749         0   
1         792          793         0    0  0.3500  0.135753         0   
2         793          794         0    1  0.3500  0.059914         1   
3         794          795         0    1  0.3125  0.015412         0   
4         795          796         0    1  0.4875  0.025374         0   

   Pclass_2  Pclass_3  Family_size  Title_1  Title_2  Title_3  Title_4  Emb_1  \
0         1         0          0.0        1        0        0        0      0   
1         0         1          1.0        0        0        0        1      0   
2         0         0          0.0        1        0        0        0      1   
3         0         1          0.0        1        0        0        0      0   
4         1         0          0.0        1        0        0        0      0   

   Emb_2  Emb_3  
0      0      1  
1      0      1  
2      0      0  
3 

In [7]:
print(df.tail())

    Unnamed: 0  PassengerId  Survived  Sex     Age      Fare  Pclass_1  \
95         886          887         0    1  0.3375  0.025374         0   
96         887          888         1    0  0.2375  0.058556         1   
97         888          889         0    0  0.3500  0.045771         0   
98         889          890         1    1  0.3250  0.058556         1   
99         890          891         0    1  0.4000  0.015127         0   

    Pclass_2  Pclass_3  Family_size  Title_1  Title_2  Title_3  Title_4  \
95         1         0          0.0        1        0        0        0   
96         0         0          0.0        0        0        0        1   
97         0         1          0.3        0        0        0        1   
98         0         0          0.0        1        0        0        0   
99         0         1          0.0        1        0        0        0   

    Emb_1  Emb_2  Emb_3  
95      0      0      1  
96      0      0      1  
97      0      0      1  


In [12]:
print("Shape of data frame\n",df.shape)

Shape of data frame
 (100, 17)


In [14]:
print("Size of Data frame\n",df.size)

Size of Data frame
 1700


In [16]:
print("Columns in Data frame\n",df.columns)

Columns in Data frame
 Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Sex', 'Age', 'Fare',
       'Pclass_1', 'Pclass_2', 'Pclass_3', 'Family_size', 'Title_1', 'Title_2',
       'Title_3', 'Title_4', 'Emb_1', 'Emb_2', 'Emb_3'],
      dtype='str')


In [11]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   100 non-null    int64  
 1   PassengerId  100 non-null    int64  
 2   Survived     100 non-null    int64  
 3   Sex          100 non-null    int64  
 4   Age          100 non-null    float64
 5   Fare         100 non-null    float64
 6   Pclass_1     100 non-null    int64  
 7   Pclass_2     100 non-null    int64  
 8   Pclass_3     100 non-null    int64  
 9   Family_size  100 non-null    float64
 10  Title_1      100 non-null    int64  
 11  Title_2      100 non-null    int64  
 12  Title_3      100 non-null    int64  
 13  Title_4      100 non-null    int64  
 14  Emb_1        100 non-null    int64  
 15  Emb_2        100 non-null    int64  
 16  Emb_3        100 non-null    int64  
dtypes: float64(3), int64(14)
memory usage: 13.4 KB
None
