In [1]:
import numpy as bat

In [2]:
import pandas as babu

In [3]:
a=bat.array([20,34,67,45,76])

In [8]:
print("View array :",a)

View array : [20 34 67 45 76]


In [9]:
print("Shape of array:",a.shape)

Shape of array: (5,)


In [13]:
b=babu.Series(['Arul','bat','babu','Thomas','suriya'])

In [14]:
print("View pandas:",b)

0      Arul
1       bat
2      babu
3    Thomas
4    suriya
dtype: str


In [16]:
d1=bat.array([23,56,77,90,100,45,23,76,54,82])
print("One Dimentional Array:",d1)

One Dimentional Array: [ 23  56  77  90 100  45  23  76  54  82]


In [24]:
multi=bat.array([[12,43,6,7,33],[45,67,99,2,54],[66,75,82,90,86]])
print("multi dimentional array:\n",multi)

multi dimentional array:
 [[12 43  6  7 33]
 [45 67 99  2 54]
 [66 75 82 90 86]]


In [23]:
zero=bat.zeros((4,5))
one=bat.ones((5,4))
print(zero)
print(one)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
